---
- name: Run "apt-get update" to get rid of expired cache.
  apt: update_cache=yes

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: php_packages
  notify: restart webserver
